/**
 * Prompt templates for edge LLM inference.
 *
 * Ported verbatim from the Python backend:
 * - slm_extractor.py (extraction)
 * - concept_meta.py (meta-classification)
 * - concept_insight_service.py (insight generation)
 */

// -- Extraction prompts (from api/src/app/nlp/slm_extractor.py) -------------

const CHUNK_EXTRACTION_SYSTEM_PROMPT = `You are filtering candidate concept phrases extracted from a note chunk.

You will receive:
- The chunk text
- A numbered list of CANDIDATES (rule-extracted noun phrases, may include false positives)
- A list of KNOWN concepts already in the user's knowledge base

Your job:
1. Pick which candidates are real, meaningful concepts. Output their indices in "keep".
2. List any clear semantic relations between kept concepts in "relations" as
   [sourceIdx, type, targetIdx] tuples.
   Use ONLY these relation types: IS_A, PART_OF, CAUSES, CONTRASTS_WITH, USES, PRODUCES, RELATED_TO.
3. Skip relations with the same source and target.
4. Be conservative — prefer fewer, high-quality picks over many noisy ones.

Return ONLY valid JSON in this shape, no markdown fences:
{ "keep": [<int>, ...], "relations": [[<int>, "<TYPE>", <int>], ...] }

KNOWN concepts (reuse where the candidate is a synonym): {known_csv}`;

/**
 * Build messages for the per-chunk LLM map step.
 *
 * Mirrors the GraphRAG/KGGen pattern: candidates over-generated by rules,
 * filtered by integer indices from the LLM. Output is bounded to ~150
 * tokens regardless of chunk size, eliminating the truncation failures
 * that plagued the one-shot extraction prompt.
 */
export function buildChunkExtractionPrompt(
  chunkText: string,
  candidates: string[],
  knownConcepts: string[],
): { system: string; user: string } {
  const knownCsv =
    knownConcepts.length > 0
      ? knownConcepts.slice(0, 100).join(", ")
      : "none yet";
  const system = CHUNK_EXTRACTION_SYSTEM_PROMPT.replace(
    "{known_csv}",
    knownCsv,
  );

  const numbered = candidates
    .map((c, i) => `${i}: ${c}`)
    .join("\n");
  const user = `CHUNK:\n${chunkText.slice(0, 1500)}\n\nCANDIDATES:\n${numbered}`;

  return { system, user };
}

// -- Summary prompt (one-sentence note summary, run after dedup) -------------

const SUMMARY_SYSTEM_PROMPT = `You write a single-sentence summary of a note for use in a knowledge graph.

Rules:
- Exactly one sentence, max 25 words.
- Capture the central topic, not a comprehensive description.
- No preamble like "This note is about...". Just the summary.
- Reference 1-2 of the key concepts when natural.

Return ONLY valid JSON, no markdown fences:
{ "summary": "<one sentence>" }`;

/**
 * Build messages for the summary step.
 *
 * Runs once after canonical concepts are known. Bounded output (~100 tokens)
 * keeps it safely under the model's budget.
 */
export function buildSummaryPrompt(
  title: string,
  content: string,
  concepts: string[],
): { system: string; user: string } {
  const conceptList =
    concepts.length > 0 ? concepts.slice(0, 12).join(", ") : "(none)";
  // Cap content to keep prefill cost predictable on long notes.
  const trimmedContent = content.length > 1500
    ? content.slice(0, 1500) + "..."
    : content;
  const user = `Title: ${title || "(untitled)"}
Key concepts: ${conceptList}

Content:
${trimmedContent}`;
  return { system: SUMMARY_SYSTEM_PROMPT, user };
}

// -- Meta-classification prompts (from api/src/app/nlp/concept_meta.py) -----

const META_SYSTEM_PROMPT = `You are a concept taxonomy assistant. Given a list of concepts from a personal \
knowledge base, identify relationships between them.

1. synonym_pairs — concepts that refer to the same idea (abbreviations, aliases, \
different phrasings). Example: "ML" and "machine learning"
2. subtopic_pairs — directed: "specific" is a specialisation of "broader". \
Example: "backpropagation" is a subtopic of "neural networks"

Rules:
- Only pair concepts from the provided list. Do not introduce outside concepts.
- Be conservative — only emit pairs you are highly confident about.
- synonym_pairs are symmetric (order does not matter).

Respond ONLY with valid JSON, no markdown fences:
{
  "synonym_pairs": [{"a": "...", "b": "..."}],
  "subtopic_pairs": [{"specific": "...", "broader": "..."}]
}`;

/**
 * Build system and user messages for meta-classification of concept pairs.
 *
 * Mirrors `ConceptMetaClassifier.classify()` in `concept_meta.py`.
 */
export function buildMetaPrompt(concepts: string[]): {
  system: string;
  user: string;
} {
  const system = META_SYSTEM_PROMPT;
  const user =
    "Concepts:\n" + concepts.map((c) => `- ${c}`).join("\n");

  return { system, user };
}

// -- Insight prompts (from api/src/app/services/concept_insight_service.py) --

const INSIGHT_SYSTEM_PROMPT = `You are a knowledge synthesis assistant. Generate an insight about a concept based \
SOLELY on the user's own notes.

Rules:
- The insight must draw only from the provided notes. Do not add external knowledge.
- Reference note titles explicitly, e.g. "In your note 'Title'...".
- Keep the insight to 2–3 focused paragraphs.
- For learning_links: suggest 3–4 genuinely reputable URLs (Wikipedia, official \
documentation, well-known academic sources). Use only real, widely-known URLs.

Respond ONLY with valid JSON in exactly this shape (no markdown fences):
{
  "insight": "...",
  "learning_links": [
    {"title": "...", "url": "https://...", "description": "..."}
  ]
}`;

/** Max chars of content passed to LLM per note context. */
const MAX_CONTENT_PER_NOTE = 600;

/**
 * Build system and user messages for concept insight generation.
 *
 * Mirrors `ConceptInsightService._call_llm()` in `concept_insight_service.py`.
 */
export function buildInsightPrompt(
  conceptLabel: string,
  noteContexts: Array<{ title: string; excerpt: string }>,
): { system: string; user: string } {
  const system = INSIGHT_SYSTEM_PROMPT;

  const parts = noteContexts.map(
    (note, i) =>
      `[Note ${i + 1}: '${note.title}']\n${note.excerpt.slice(0, MAX_CONTENT_PER_NOTE)}`,
  );
  const context = parts.join("\n\n---\n\n");

  const user = `Concept to analyse: "${conceptLabel}"\n\nUser notes mentioning this concept:\n\n${context}`;

  return { system, user };
}
