from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

REQUIRED_DIRS = [
    "api",
    "api/alembic",
    "api/alembic/versions",
    "api/src/app/db",
    "api/src/app/db/models",
    "api/src/app/db/repositories",
    "api/src/app/core",
    "api/src/app/nlp",
    "api/src/app/nlp/resolution",
    "api/src/app/media",
    "api/src/app/export",
    "api/src/app/routes",
    "api/src/app/services",
    "shared/contracts/python/v1",
    "shared/contracts/ts/v1",
    "web/src/app",
    "web/src/components/editor",
    "web/src/components/graph",
    "web/src/components/workspace",
    "web/src/lib/editor",
    "web/src/lib/editor/extensions",
    "web/src/lib",
    "web/src/lib/workspace",
    "web/src/lib/orchestration",
    "web/src/lib/state",
    "web/src/lib/timing",
    "infra",
    "infra/db",
    "infra/sql",
    "tests/unit",
    "tests/integration",
    "tests/e2e",
]

REQUIRED_FILES = [
    ".gitignore",
    "Makefile",
    "api/alembic.ini",
    "api/alembic/env.py",
    "api/alembic/script.py.mako",
    "api/alembic/versions/20260301_0001_core_tables.py",
    "api/alembic/versions/20260307_0002_entity_aliases.py",
    "api/alembic/versions/20260311_0003_note_title.py",
    "api/alembic/versions/20260312_0004_workspace_organization.py",
    "api/alembic/versions/20260313_0005_note_assets.py",
    "api/alembic/versions/20260314_0007_note_assets_repair.py",
    "api/pyproject.toml",
    "api/.env.example",
    "api/src/app/main.py",
    "api/src/app/routes/health.py",
    "api/src/app/routes/notes.py",
    "api/src/app/routes/process.py",
    "api/src/app/routes/entity_aliases.py",
    "api/src/app/routes/backfill.py",
    "api/src/app/routes/media.py",
    "api/src/app/routes/export.py",
    "api/src/app/routes/graph.py",
    "api/src/app/nlp/config.py",
    "api/src/app/nlp/embeddings.py",
    "api/src/app/nlp/pipeline.py",
    "api/src/app/nlp/types.py",
    "api/src/app/nlp/resolution/__init__.py",
    "api/src/app/nlp/resolution/normalization.py",
    "api/src/app/nlp/resolution/abbreviation.py",
    "api/src/app/nlp/resolution/fuzzy.py",
    "api/src/app/nlp/resolution/embedding.py",
    "api/src/app/nlp/resolution/resolver.py",
    "api/src/app/services/note_processing_service.py",
    "api/src/app/services/graph_sync_service.py",
    "api/src/app/services/startup_backfill_service.py",
    "api/src/app/services/note_asset_service.py",
    "api/src/app/services/local_graph_service.py",
    "api/src/app/core/backfill_store.py",
    "api/src/app/media/config.py",
    "api/src/app/media/storage.py",
    "api/src/app/media/local_storage.py",
    "api/src/app/media/references.py",
    "api/src/app/export/markdown.py",
    "api/src/app/db/config.py",
    "api/src/app/db/engine.py",
    "api/src/app/db/session.py",
    "api/src/app/db/extensions.py",
    "api/src/app/db/bootstrap_entity_aliases.py",
    "api/src/app/db/models/base.py",
    "api/src/app/db/models/subject.py",
    "api/src/app/db/models/note.py",
    "api/src/app/db/models/block.py",
    "api/src/app/db/models/tag.py",
    "api/src/app/db/models/entity_alias.py",
    "api/src/app/db/models/note_tag.py",
    "api/src/app/db/models/note_asset.py",
    "api/src/app/db/repositories/note_repository.py",
    "api/src/app/db/repositories/graph_repository.py",
    "api/src/app/db/repositories/block_repository.py",
    "api/src/app/db/repositories/subject_repository.py",
    "api/src/app/db/repositories/tag_repository.py",
    "api/src/app/db/repositories/entity_alias_repository.py",
    "api/src/app/db/repositories/note_asset_repository.py",
    "shared/contracts/python/v1/note.py",
    "shared/contracts/python/v1/process.py",
    "shared/contracts/python/v1/entity_alias.py",
    "shared/contracts/python/v1/backfill.py",
    "shared/contracts/python/v1/media.py",
    "shared/contracts/python/v1/export.py",
    "shared/contracts/python/v1/graph.py",
    "shared/contracts/ts/v1/note.ts",
    "shared/contracts/ts/v1/process.ts",
    "shared/contracts/ts/v1/entity-alias.ts",
    "shared/contracts/ts/v1/backfill.ts",
    "shared/contracts/ts/v1/media.ts",
    "shared/contracts/ts/v1/export.ts",
    "shared/contracts/ts/v1/graph.ts",
    "shared/contracts/README.md",
    "web/package.json",
    "web/next-env.d.ts",
    "web/vitest.config.ts",
    "web/src/app/layout.tsx",
    "web/src/app/page.tsx",
    "web/src/components/editor/EditorToolbar.tsx",
    "web/src/components/editor/NoteEditor.tsx",
    "web/src/components/editor/TipTapEditor.tsx",
    "web/src/components/workspace/NotesWorkspace.test.tsx",
    "web/src/components/workspace/NotesWorkspace.tsx",
    "web/src/components/graph/LocalGraphPanel.tsx",
    "web/src/components/graph/LocalGraphPanel.test.tsx",
    "web/src/lib/api-client.ts",
    "web/src/lib/workspace/types.ts",
    "web/src/lib/editor/serialize.ts",
    "web/src/lib/editor/text-extract.ts",
    "web/src/lib/editor/math.ts",
    "web/src/lib/editor/math-render.ts",
    "web/src/lib/editor/extensions/math-inline.ts",
    "web/src/lib/editor/extensions/math-block.ts",
    "web/src/lib/editor/extensions/image-node.ts",
    "web/src/lib/orchestration/note-lifecycle.ts",
    "web/src/lib/orchestration/process-polling.ts",
    "web/src/lib/state/note-store.ts",
    "web/src/lib/timing/debounce.ts",
    "infra/docker-compose.yml",
    "infra/db/Dockerfile",
    "infra/sql/001-enable-extensions.sql",
    "tests/integration/test_graph_vector_repository.py",
    "tests/integration/test_backfill_api.py",
    "tests/integration/test_process_api.py",
    "tests/integration/test_graph_api.py",
    "tests/integration/test_media_api.py",
    "tests/unit/test_note_processing_service.py",
    "tests/unit/test_note_asset_repository.py",
    "tests/unit/test_note_asset_service.py",
    "tests/unit/test_note_assets_migration.py",
    "tests/unit/test_note_assets_repair_migration.py",
    "tests/unit/test_media_contracts.py",
    "tests/unit/test_markdown_export.py",
    "tests/unit/test_graph_sync_service.py",
    "tests/unit/test_local_graph_service.py",
    "tests/unit/test_graph_contracts.py",
    "tests/unit/test_note_title_migration.py",
    "tests/unit/test_workspace_organization_migration.py",
    "tests/unit/test_startup_backfill_service.py",
    "tests/unit/test_job_store.py",
    "web/src/lib/editor/math-render.test.ts",
    ".github/workflows/ci.yml",
]


def test_required_directories_exist() -> None:
    for rel in REQUIRED_DIRS:
        path = ROOT / rel
        assert path.is_dir(), f"Missing required directory: {rel}"


def test_required_files_exist() -> None:
    for rel in REQUIRED_FILES:
        path = ROOT / rel
        assert path.is_file(), f"Missing required file: {rel}"
